#pragma once
// Auto-generated fixed matching conditions
// DO NOT EDIT - Generated by gen_conditions.py
//
// Prefix patterns: "4eq"
// Suffix patterns: "AAAA"

__device__ __forceinline__ bool match_prefix_fixed(const uint32_t* hash) {
    if ((hash[0] & 0xFFFFC000U) != 0xE1EA8000U) return false;
    return true;
}

__device__ __forceinline__ bool match_suffix_fixed(const uint32_t* hash) {
    if ((hash[7] & 0x003FFFFFU) != 0x00000000U) return false;
    return true;
}
