#pragma once
// Auto-generated fixed matching conditions
// DO NOT EDIT - Generated by gen_conditions.py
//
// Prefix patterns: none
// Suffix patterns: "4eques"

__device__ __forceinline__ bool match_suffix_fixed(const uint32_t* hash) {
    if ((hash[6] & 0x00000003U) != 0x00000003U) return false;
    if (hash[7] != 0x87AAB9EBU) return false;
    return true;
}
