#pragma once
// Auto-generated fixed matching conditions
// DO NOT EDIT - Generated by gen_conditions.py
//
// Prefix patterns: none
// Suffix patterns: "A", "AAAA"

__device__ __forceinline__ bool match_suffix_fixed(const uint32_t* hash) {
    return [&]() { if ((hash[7] & 0x0000000FU) != 0x00000000U) return false; return true; }() || [&]() { if ((hash[7] & 0x003FFFFFU) != 0x00000000U) return false; return true; }();
}
